name: CI-write-output-official
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Read version from repository
        id: read-file
        shell: pwsh
        run: |
            $content = Get-Content -Path version.txt -Raw
            echo outputContent=$content >> $env:GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}
      - name: Print version from file to console
        id: write-content
        shell: pwsh
        run: |
            echo "version: ${{ steps.read-file.outputs.outputContent }}"
        